spring:
  cloud:
    stream:
      bindings:
        user_create_input:
          destination: ex.stream.user.create.in
          binder: rabbit1
        user_create_output:
          destination: ex.stream.user.create.out
          binder: rabbit1
        user_update_input:
          destination: ex.stream.user.update.in
          binder: rabbit1
        user_update_output:
          destination: ex.stream.user.update.out
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
management:
  health:
    binders:
      enabled: true
