spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.user.in
          group: user
          binder: rabbit1
        output:
          destination: ex.stream.user.out
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
management:
  health:
    binders:
      enabled: true
