spring:
  cloud:
    stream:
      bindings:
        movie_create_input:
          destination: ex.stream.movie.create.out
          binder: rabbit1
        movie_create_output:
          destination: ex.stream.movie.create.in
          binder: rabbit1
        movie_update_input:
          destination: ex.stream.movie.update.out
          binder: rabbit1
        movie_update_output:
          destination: ex.stream.movie.update.in
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
management:
  health:
    binders:
      enabled: true
